"""This module holds `TABLE_2`, the test problems of Table 2 of the 2026 modAB paper, with modAB's evaluation
count in that table and its root in the paper's supplementary results.

The functions follow the C# benchmark of the paper's supplementary code, which produced Table 2; where the table
prints a function differently, the C# code holds.

Each power and each library function other than ``sqrt``, ``ceil`` and ``floor``, such as ``exp`` or ``sin``, is
evaluated correctly rounded, through mpmath; IEEE 754 already rounds ``sqrt`` correctly, and ``ceil`` and ``floor`` are
exact.

The C library rounds the last bit of powers and library functions differently per platform, and on several of the 92
functions that last bit changes the evaluation count; correctly rounded values make the counts the same on every
platform.
"""

import math
from collections.abc import Callable

import mpmath

from tests.solvers.paper_problems import PaperProblem


# ==================================================================================================
#  Helpers
# ==================================================================================================
def _correctly_rounded(mpmath_function: Callable[..., mpmath.mpf]) -> Callable[..., float]:
    """Return a float version of ``mpmath_function`` that rounds its exact result to the nearest float.

    With 160 bits of working precision, the result is rounded correctly unless the exact value lies within a relative
    distance of 2^-107 of the midpoint between 2 adjacent floats.
    """

    def evaluate(*args: float) -> float:
        with mpmath.workprec(160):
            return float(mpmath_function(*[mpmath.mpf(arg) for arg in args]))

    return evaluate


_atan = _correctly_rounded(mpmath.atan)
_cbrt = _correctly_rounded(mpmath.cbrt)
_cos = _correctly_rounded(mpmath.cos)
_exp = _correctly_rounded(mpmath.exp)
_log = _correctly_rounded(mpmath.log)
_pow = _correctly_rounded(mpmath.power)
_sin = _correctly_rounded(mpmath.sin)
_tan = _correctly_rounded(mpmath.tan)


def _f27(x: float) -> float:
    """Return ``f27``, a quartic in ``s = x + 1.11111`` whose sign flips where ``s = 3``."""
    s = x + 1.11111
    return (81 - s * (108 - s * (54 - s * (12 - s)))) * float(mpmath.sign(s - 3))


# ==================================================================================================
#  The problems
# ==================================================================================================
# On the problems whose row carries this reason, the evaluation count differs from Table 2's, presumably because the
# authors' .NET runtime rounds the last bit of cos, cbrt or exp differently from the correctly rounded values here,
# which changes the x-values that the solve evaluates.
_ROUNDING_DEVIATION_REASON = (
    "the .NET runtime of the paper's benchmark presumably rounds a library function differently"
)

# Each row holds:
# - the function's name in Table 2, f01 to f92;
# - the function and its interval;
# - modAB's root in the paper's supplementary results; `ModAB` returns this x-value without evaluating the function
#   there;
# - modAB's evaluation count in Table 2;
# - the number of iterations whose chord's zero is clamped onto a bound: the paper's C# code counts every iteration as
#   an evaluation, but a clamped iteration evaluates nothing, so `ModAB`'s evaluation count is the table's count minus
#   the clamped iterations.
# A row whose count `ModAB` does not reproduce exactly also holds a count tolerance and the reason.
TABLE_2 = [
    PaperProblem(
        name=row["name"],
        f=row["f"],
        a=row["a"],
        b=row["b"],
        root=row["root"],
        root_rel_tol=1e-13,
        n_fevals=row["reported_n_fevals"] - row["n_clamped"],
        n_fevals_tol=row.get("n_fevals_tol", 0),
        deviation_reason=row.get("deviation_reason"),
    )
    for row in [
        {
            "name": "f01",
            "f": lambda x: _pow(x, 3) - 1,
            "a": 0.5,
            "b": 1.5,
            "root": 1.0,
            "reported_n_fevals": 3,
            "n_clamped": 0,
        },
        {
            "name": "f02",
            "f": lambda x: _pow(x, 2) * (_pow(x, 2) / 3 + math.sqrt(2) * _sin(x)) - math.sqrt(3) / 18,
            "a": 0.1,
            "b": 1.0,
            "root": 0.399422291710968,
            "reported_n_fevals": 12,
            "n_clamped": 0,
        },
        {
            "name": "f03",
            "f": lambda x: 11 * _pow(x, 11) - 1,
            "a": 0.1,
            "b": 1.0,
            "root": 0.804133097503664,
            "reported_n_fevals": 15,
            "n_clamped": 2,
        },
        {
            "name": "f04",
            "f": lambda x: _pow(x, 3) + 1,
            "a": -1.8,
            "b": 0.0,
            "root": -1.0,
            "reported_n_fevals": 10,
            "n_clamped": 0,
        },
        {
            "name": "f05",
            "f": lambda x: _pow(x, 3) - 2 * x - 5,
            "a": 2.0,
            "b": 3.0,
            "root": 2.09455148154232,
            "reported_n_fevals": 12,
            "n_clamped": 2,
        },
        {
            "name": "f06",
            "f": lambda x: 2 * x * _exp(-5) + 1 - 2 * _exp(-5 * x),
            "a": 0.0,
            "b": 1.0,
            "root": 0.138257155056824,
            "reported_n_fevals": 10,
            "n_clamped": 0,
        },
        {
            "name": "f07",
            "f": lambda x: 2 * x * _exp(-10) + 1 - 2 * _exp(-10 * x),
            "a": 0.0,
            "b": 1.0,
            "root": 0.0693140886870234,
            "reported_n_fevals": 11,
            "n_clamped": 0,
        },
        {
            "name": "f08",
            "f": lambda x: 2 * x * _exp(-20) + 1 - 2 * _exp(-20 * x),
            "a": 0.0,
            "b": 1.0,
            "root": 0.0346573590208538,
            "reported_n_fevals": 12,
            "n_clamped": 0,
        },
        {
            "name": "f09",
            "f": lambda x: (1 + _pow(1 - 5, 2)) * _pow(x, 2) - _pow(1 - 5 * x, 2),
            "a": 0.0,
            "b": 1.0,
            "root": 0.109611796797792,
            "reported_n_fevals": 11,
            "n_clamped": 1,
        },
        {
            "name": "f10",
            "f": lambda x: (1 + _pow(1 - 10, 2)) * _pow(x, 2) - _pow(1 - 10 * x, 2),
            "a": 0.0,
            "b": 1.0,
            "root": 0.0524786034368101,
            "reported_n_fevals": 9,
            "n_clamped": 0,
        },
        {
            "name": "f11",
            "f": lambda x: (1 + _pow(1 - 20, 2)) * _pow(x, 2) - _pow(1 - 20 * x, 2),
            "a": 0.0,
            "b": 1.0,
            "root": 0.0256237476199882,
            "reported_n_fevals": 9,
            "n_clamped": 0,
        },
        {
            "name": "f12",
            "f": lambda x: _pow(x, 2) - _pow(1 - x, 5),
            "a": 0.0,
            "b": 1.0,
            "root": 0.345954815848242,
            "reported_n_fevals": 11,
            "n_clamped": 0,
        },
        {
            "name": "f13",
            "f": lambda x: _pow(x, 2) - _pow(1 - x, 10),
            "a": 0.0,
            "b": 1.0,
            "root": 0.245122333753307,
            "reported_n_fevals": 12,
            "n_clamped": 0,
        },
        {
            "name": "f14",
            "f": lambda x: _pow(x, 2) - _pow(1 - x, 20),
            "a": 0.0,
            "b": 1.0,
            "root": 0.16492095727644,
            "reported_n_fevals": 12,
            "n_clamped": 0,
        },
        {
            "name": "f15",
            "f": lambda x: (1 + _pow(1 - 5, 4)) * x - _pow(1 - 5 * x, 4),
            "a": 0.0,
            "b": 1.0,
            "root": 0.00361710817890406,
            "reported_n_fevals": 9,
            "n_clamped": 0,
        },
        {
            "name": "f16",
            "f": lambda x: (1 + _pow(1 - 10, 4)) * x - _pow(1 - 10 * x, 4),
            "a": 0.0,
            "b": 1.0,
            "root": 0.000151471334783891,
            "reported_n_fevals": 8,
            "n_clamped": 0,
        },
        {
            "name": "f17",
            "f": lambda x: (1 + _pow(1 - 20, 4)) * x - _pow(1 - 20 * x, 4),
            "a": 0.0,
            "b": 1.0,
            "root": 7.66859512218533e-06,
            "reported_n_fevals": 8,
            "n_clamped": 0,
        },
        {
            "name": "f18",
            "f": lambda x: _exp(-5 * x) * (x - 1) + _pow(x, 5),
            "a": 0.0,
            "b": 1.0,
            "root": 0.516153518757933,
            "reported_n_fevals": 11,
            "n_clamped": 0,
        },
        {
            "name": "f19",
            "f": lambda x: _exp(-10 * x) * (x - 1) + _pow(x, 10),
            "a": 0.0,
            "b": 1.0,
            "root": 0.539522226908415,
            "reported_n_fevals": 12,
            "n_clamped": 0,
        },
        {
            "name": "f20",
            "f": lambda x: _exp(-20 * x) * (x - 1) + _pow(x, 20),
            "a": 0.0,
            "b": 1.0,
            "root": 0.552704666678487,
            "reported_n_fevals": 14,
            "n_clamped": 1,
        },
        {
            "name": "f21",
            "f": lambda x: _pow(x, 2) + _sin(x / 5) - 1 / 4,
            "a": 0.0,
            "b": 1.0,
            "root": 0.409992017989137,
            "reported_n_fevals": 9,
            "n_clamped": 0,
        },
        {
            "name": "f22",
            "f": lambda x: _pow(x, 2) + _sin(x / 10) - 1 / 4,
            "a": 0.0,
            "b": 1.0,
            "root": 0.452509145577641,
            "reported_n_fevals": 9,
            "n_clamped": 0,
        },
        {
            "name": "f23",
            "f": lambda x: _pow(x, 2) + _sin(x / 20) - 1 / 4,
            "a": 0.0,
            "b": 1.0,
            "root": 0.475626848596062,
            "reported_n_fevals": 9,
            "n_clamped": 0,
        },
        {
            "name": "f24",
            "f": lambda x: (x + 2) * (x + 1) * _pow(x - 3, 3),
            "a": 2.6,
            "b": 4.6,
            "root": 2.99999999999999,
            "reported_n_fevals": 48,
            "n_clamped": 0,
        },
        {
            "name": "f25",
            "f": lambda x: _pow(x - 4, 5) * _log(x),
            "a": 3.6,
            "b": 5.6,
            "root": 3.99999999999999,
            "reported_n_fevals": 48,
            "n_clamped": 0,
        },
        {
            "name": "f26",
            "f": lambda x: _pow(_sin(x) - x / 4, 3),
            "a": 2.0,
            "b": 4.0,
            "root": 2.47457678736982,
            "reported_n_fevals": 48,
            "n_clamped": 0,
        },
        {"name": "f27", "f": _f27, "a": 1.0, "b": 3.0, "root": 1.88916015625, "reported_n_fevals": 14, "n_clamped": 0},
        {
            "name": "f28",
            "f": lambda x: _sin(_pow(x - 7.143, 3)),
            "a": 7.0,
            "b": 8.0,
            "root": 7.143,
            "reported_n_fevals": 46,
            "n_clamped": 0,
        },
        {
            "name": "f29",
            "f": lambda x: _exp(_pow(x - 3, 5)) - 1,
            "a": 2.6,
            "b": 4.6,
            "root": 3.00039062499999,
            "reported_n_fevals": 12,
            "n_clamped": 0,
        },
        {
            "name": "f30",
            "f": lambda x: _exp(_pow(x - 3, 5)) - _exp(x - 1),
            "a": 4.0,
            "b": 5.0,
            "root": 4.26716830454212,
            "reported_n_fevals": 13,
            "n_clamped": 0,
        },
        {
            "name": "f31",
            "f": lambda x: math.pi - 1 / x,
            "a": 0.05,
            "b": 5.0,
            "root": 0.31830988618379,
            "reported_n_fevals": 12,
            "n_clamped": 0,
        },
        {
            "name": "f32",
            "f": lambda x: 4 - _tan(x),
            "a": 0.0,
            "b": 1.5,
            "root": 1.32581766366803,
            "reported_n_fevals": 14,
            "n_clamped": 1,
        },
        {
            "name": "f33",
            "f": lambda x: _cos(x) - _pow(x, 3),
            "a": 0.0,
            "b": 4.0,
            "root": 0.865474033101614,
            "reported_n_fevals": 12,
            "n_clamped": 0,
        },
        {
            "name": "f34",
            "f": lambda x: _cos(x) - x,
            "a": -11.0,
            "b": 9.0,
            "root": 0.73908513321516,
            "reported_n_fevals": 11,
            "n_clamped": 0,
            "n_fevals_tol": 4,
            "deviation_reason": _ROUNDING_DEVIATION_REASON,
        },
        {
            "name": "f35",
            "f": lambda x: math.sqrt(abs(x - 2 / 3)) * (1 if x <= 2 / 3 else -1) - 0.1,
            "a": -11.0,
            "b": 9.0,
            "root": 0.656666666666666,
            "reported_n_fevals": 17,
            "n_clamped": 1,
        },
        {
            "name": "f36",
            "f": lambda x: _pow(abs(x - 2 / 3), 0.2) * (1 if x <= 2 / 3 else -1),
            "a": -11.0,
            "b": 9.0,
            "root": 0.666666666666665,
            "reported_n_fevals": 55,
            "n_clamped": 0,
        },
        {
            "name": "f37",
            "f": lambda x: _pow(x - 7 / 9, 3) + (x - 7 / 9) * 1e-3,
            "a": -11.0,
            "b": 9.0,
            "root": 0.777777777777777,
            "reported_n_fevals": 16,
            "n_clamped": 0,
        },
        {
            "name": "f38",
            "f": lambda x: -0.5 if x <= 1 / 3 else 0.5,
            "a": -11.0,
            "b": 9.0,
            "root": 0.333333333333333,
            "reported_n_fevals": 53,
            "n_clamped": 0,
        },
        {
            "name": "f39",
            "f": lambda x: -1e-3 if x <= 1 / 3 else 1 - 1e-3,
            "a": -11.0,
            "b": 9.0,
            "root": 0.333333333333333,
            "reported_n_fevals": 53,
            "n_clamped": 0,
        },
        {
            "name": "f40",
            "f": lambda x: 0.0 if x == 0 else 1 / (x - 2 / 3),
            "a": -11.0,
            "b": 9.0,
            "root": 0.666666666666665,
            "reported_n_fevals": 53,
            "n_clamped": 0,
        },
        {
            "name": "f41",
            "f": lambda x: 2 * x * _exp(-5) - 2 * _exp(-5 * x) + 1,
            "a": 0.0,
            "b": 10.0,
            "root": 0.138257155056824,
            "reported_n_fevals": 13,
            "n_clamped": 0,
        },
        {
            "name": "f42",
            "f": lambda x: (_pow(x, 2) - x - 6) * (_pow(x, 2) - 3 * x + 2),
            "a": 0.0,
            "b": math.pi,
            "root": 1.0,
            "reported_n_fevals": 12,
            "n_clamped": 0,
        },
        {
            "name": "f43",
            "f": lambda x: _pow(x, 3),
            "a": -1.0,
            "b": 1.5,
            "root": 8.88178419700125e-16,
            "reported_n_fevals": 50,
            "n_clamped": 0,
        },
        {
            "name": "f44",
            "f": lambda x: _pow(x, 5),
            "a": -1.0,
            "b": 1.5,
            "root": 8.88178419700125e-16,
            "reported_n_fevals": 50,
            "n_clamped": 0,
        },
        {
            "name": "f45",
            "f": lambda x: _pow(x, 7),
            "a": -1.0,
            "b": 1.5,
            "root": 8.88178419700125e-16,
            "reported_n_fevals": 50,
            "n_clamped": 0,
        },
        {
            "name": "f46",
            "f": lambda x: (_exp(-5 * x) - x - 0.5) / _pow(x, 5),
            "a": 0.09,
            "b": 0.7,
            "root": 0.101624392293549,
            "reported_n_fevals": 14,
            "n_clamped": 0,
        },
        {
            "name": "f47",
            "f": lambda x: 1 / math.sqrt(x) - 2 * _log(5e3 * math.sqrt(x)) + 0.8,
            "a": 0.0005,
            "b": 0.5,
            "root": 0.00773252320061279,
            "reported_n_fevals": 16,
            "n_clamped": 0,
        },
        {
            "name": "f48",
            "f": lambda x: 1 / math.sqrt(x) - 2 * _log(5e7 * math.sqrt(x)) + 0.8,
            "a": 0.0005,
            "b": 0.5,
            "root": 0.00127630494573556,
            "reported_n_fevals": 14,
            "n_clamped": 0,
        },
        {
            "name": "f49",
            "f": lambda x: -_pow(x, 3) - x - 1 if x <= 0 else _pow(x, 0) - x - 1,
            "a": -1.0,
            "b": 1.0,
            "root": -0.682327803828019,
            "reported_n_fevals": 12,
            "n_clamped": 1,
        },
        {
            "name": "f50",
            "f": lambda x: _pow(x, 3) - 2 * x - x + 3,
            "a": -3.0,
            "b": 2.0,
            "root": -2.10380340273553,
            "reported_n_fevals": 11,
            "n_clamped": 0,
        },
        {"name": "f51", "f": _log, "a": 0.5, "b": 5.0, "root": 1.0, "reported_n_fevals": 10, "n_clamped": 0},
        {
            "name": "f52",
            "f": lambda x: (10 - x) * _exp(-10 * x) - _pow(x, 10) + 1,
            "a": 0.5,
            "b": 8.0,
            "root": 1.00004083556472,
            "reported_n_fevals": 15,
            "n_clamped": 0,
        },
        {
            "name": "f53",
            "f": lambda x: _exp(_sin(x)) - x - 1,
            "a": 1.0,
            "b": 4.0,
            "root": 1.69681238680975,
            "reported_n_fevals": 13,
            "n_clamped": 0,
        },
        {
            "name": "f54",
            "f": lambda x: 2 * _sin(x) - 1,
            "a": 0.1,
            "b": math.pi / 3,
            "root": 0.523598775598298,
            "reported_n_fevals": 11,
            "n_clamped": 1,
        },
        {
            "name": "f55",
            "f": lambda x: (x - 1) * _exp(-x),
            "a": 0.0,
            "b": 1.5,
            "root": 1.0,
            "reported_n_fevals": 10,
            "n_clamped": 0,
        },
        {
            "name": "f56",
            "f": lambda x: _pow(x - 1, 3) - 1,
            "a": 1.5,
            "b": 3.0,
            "root": 2.0,
            "reported_n_fevals": 11,
            "n_clamped": 0,
        },
        {
            "name": "f57",
            "f": lambda x: _exp(_pow(x, 2) + 7 * x - 30) - 1,
            "a": 2.6,
            "b": 3.5,
            "root": 3.0,
            "reported_n_fevals": 11,
            "n_clamped": 0,
        },
        {
            "name": "f58",
            "f": lambda x: _atan(x) - 1,
            "a": 1.0,
            "b": 8.0,
            "root": 1.5574077246549,
            "reported_n_fevals": 10,
            "n_clamped": 0,
        },
        {
            "name": "f59",
            "f": lambda x: _exp(x) - 2 * x - 1,
            "a": 0.2,
            "b": 3.0,
            "root": 1.25643120862616,
            "reported_n_fevals": 12,
            "n_clamped": 0,
        },
        {
            "name": "f60",
            "f": lambda x: _exp(-x) - x - _sin(x),
            "a": 0.0,
            "b": 2.0,
            "root": 0.354463104375025,
            "reported_n_fevals": 9,
            "n_clamped": 0,
        },
        {
            "name": "f61",
            "f": lambda x: _pow(x, 2) - _pow(_sin(x), 2) - 1,
            "a": -1.0,
            "b": 2.0,
            "root": 1.40449164821534,
            "reported_n_fevals": 13,
            "n_clamped": 1,
        },
        {
            "name": "f62",
            "f": lambda x: _sin(x) - x / 2,
            "a": math.pi / 2,
            "b": math.pi,
            "root": 1.89549426703398,
            "reported_n_fevals": 10,
            "n_clamped": 0,
        },
        {
            "name": "f63",
            "f": lambda x: x * _exp(x) - 1,
            "a": -1.0,
            "b": 1.0,
            "root": 0.567143290409783,
            "reported_n_fevals": 11,
            "n_clamped": 0,
        },
        {
            "name": "f64",
            "f": lambda x: _tan(x - 1 / 10),
            "a": -1.0,
            "b": 1.0,
            "root": 0.1,
            "reported_n_fevals": 8,
            "n_clamped": 0,
        },
        {
            "name": "f65",
            "f": lambda x: _sin(x) + 0.5,
            "a": -1.0,
            "b": 1.0,
            "root": -0.523598775598298,
            "reported_n_fevals": 9,
            "n_clamped": 0,
        },
        {
            "name": "f66",
            "f": lambda x: 4 * _pow(x, 5) + x * x + 1,
            "a": -1.0,
            "b": 1.0,
            "root": -0.843914568649266,
            "reported_n_fevals": 13,
            "n_clamped": 0,
        },
        {
            "name": "f67",
            "f": lambda x: x + _pow(x, 10) - 1,
            "a": -1.0,
            "b": 1.0,
            "root": 0.835079042723559,
            "reported_n_fevals": 12,
            "n_clamped": 0,
        },
        {
            "name": "f68",
            "f": lambda x: _pow(math.pi, x) - math.e,
            "a": -1.0,
            "b": 1.0,
            "root": 0.873568526830231,
            "reported_n_fevals": 9,
            "n_clamped": 0,
        },
        {
            "name": "f69",
            "f": lambda x: _log(abs(x - 10 / 9)),
            "a": -1.0,
            "b": 1.0,
            "root": 0.111111111111111,
            "reported_n_fevals": 10,
            "n_clamped": 0,
        },
        {
            "name": "f70",
            "f": lambda x: 1 / 3 + float(mpmath.sign(x)) * _cbrt(abs(x)) + _pow(x, 3),
            "a": -1.0,
            "b": 1.0,
            "root": -0.0370201277078609,
            "reported_n_fevals": 17,
            "n_clamped": 1,
            "n_fevals_tol": 4,
            "deviation_reason": _ROUNDING_DEVIATION_REASON,
        },
        {
            "name": "f71",
            "f": lambda x: (x + 2 / 3) / (x + 101 / 100),
            "a": -1.0,
            "b": 1.0,
            "root": -0.666666666666666,
            "reported_n_fevals": 8,
            "n_clamped": 0,
        },
        {
            "name": "f72",
            "f": lambda x: _pow(x * 1e6 - 1, 3),
            "a": -1.0,
            "b": 1.0,
            "root": 1.00000000102795e-06,
            "reported_n_fevals": 50,
            "n_clamped": 0,
        },
        {
            "name": "f73",
            "f": lambda x: _exp(x) * _pow(x * 1e6 - 1, 3),
            "a": -1.0,
            "b": 1.0,
            "root": 1.00000000102795e-06,
            "reported_n_fevals": 50,
            "n_clamped": 0,
        },
        {
            "name": "f74",
            "f": lambda x: _pow(x - 1 / 3, 2) * _atan(x - 1 / 3),
            "a": -1.0,
            "b": 1.0,
            "root": 0.333333333333332,
            "reported_n_fevals": 50,
            "n_clamped": 0,
        },
        {
            "name": "f75",
            "f": lambda x: float(mpmath.sign(3 * x - 1)) * (1 - math.sqrt(1 - _pow(3 * x - 1, 2) / 81)),
            "a": -1.0,
            "b": 1.0,
            "root": 0.333333313465118,
            "reported_n_fevals": 27,
            "n_clamped": 0,
        },
        {
            "name": "f76",
            "f": lambda x: (1 + 1e6) / 1e6 if x > (1 - 1e6) / 1e6 else -1.0,
            "a": -1.0,
            "b": 1.0,
            "root": -0.999999000000003,
            "reported_n_fevals": 39,
            "n_clamped": 0,
        },
        {
            "name": "f77",
            "f": lambda x: 1 / (21 * x - 1) if x != 1 / 21 else 0.0,
            "a": -1.0,
            "b": 1.0,
            "root": 0.0476190476190474,
            "reported_n_fevals": 50,
            "n_clamped": 0,
        },
        {
            "name": "f78",
            "f": lambda x: x * x / 4 + math.ceil(x / 2) - 0.5,
            "a": -1.0,
            "b": 1.0,
            "root": 9.65733148895921e-43,
            "reported_n_fevals": 9,
            "n_clamped": 0,
        },
        {
            "name": "f79",
            "f": lambda x: math.ceil(10 * x - 1) + 0.5,
            "a": -1.0,
            "b": 1.0,
            "root": 2.91317086684747e-19,
            "reported_n_fevals": 14,
            "n_clamped": 0,
        },
        {
            "name": "f80",
            "f": lambda x: x + _sin(x * 1e6) / 10 + 1e-3,
            "a": -1.0,
            "b": 1.0,
            "root": -0.0414560401586836,
            "reported_n_fevals": 25,
            "n_clamped": 0,
        },
        {
            "name": "f81",
            "f": lambda x: 1 + _sin(1 / (x + 1)) if x > -1 else -1.0,
            "a": -1.0,
            "b": 1.0,
            "root": -1.0,
            "reported_n_fevals": 14,
            "n_clamped": 0,
        },
        {
            "name": "f82",
            "f": lambda x: 202 * x - 2 * math.floor((2 * x + 1e-2) / 2e-2) - 0.1,
            "a": -1.0,
            "b": 1.0,
            "root": 0.0499999999999999,
            "reported_n_fevals": 5,
            "n_clamped": 0,
        },
        {
            "name": "f83",
            "f": lambda x: _pow(202 * x - 2 * math.floor((2 * x + 1e-2) / 2e-2) - 0.1, 3),
            "a": -1.0,
            "b": 1.0,
            "root": 0.198514851485146,
            "reported_n_fevals": 50,
            "n_clamped": 0,
        },
        {
            "name": "f84",
            "f": lambda x: (x - 1) * (x - 2) * (x - 3) * (x - 4) * (x - 5) - 0.05,
            "a": 0.5,
            "b": 5.5,
            "root": 3.01250244276146,
            "reported_n_fevals": 8,
            "n_clamped": 0,
        },
        {
            "name": "f85",
            "f": lambda x: _sin(x) - 0.5 * x - 0.3,
            "a": -10.0,
            "b": 10.0,
            "root": -2.20778314488693,
            "reported_n_fevals": 11,
            "n_clamped": 0,
        },
        {
            "name": "f86",
            "f": lambda x: _exp(x) - 1 - x - x * x / 2 - 0.005,
            "a": -2.0,
            "b": 2.0,
            "root": 0.302804157270697,
            "reported_n_fevals": 15,
            "n_clamped": 0,
            "n_fevals_tol": 4,
            "deviation_reason": _ROUNDING_DEVIATION_REASON,
        },
        {
            "name": "f87",
            "f": lambda x: 1 / (x - 0.5) - 2 - 0.05,
            "a": 0.6,
            "b": 2.0,
            "root": 0.98780487804878,
            "reported_n_fevals": 9,
            "n_clamped": 1,
        },
        {
            "name": "f88",
            "f": lambda x: _log(x) - x + 2 - 0.05,
            "a": 0.1,
            "b": 3.0,
            "root": 0.168362173262536,
            "reported_n_fevals": 14,
            "n_clamped": 1,
        },
        {
            "name": "f89",
            "f": lambda x: _sin(20 * x) + 0.1 * x - 0.1,
            "a": -4.0,
            "b": 5.0,
            "root": -1.74176261121641,
            "reported_n_fevals": 13,
            "n_clamped": 0,
        },
        {
            "name": "f90",
            "f": lambda x: x * x * x - 2 * x * x + x - 0.025,
            "a": -1.0,
            "b": 2.0,
            "root": 0.02637269541443,
            "reported_n_fevals": 13,
            "n_clamped": 0,
        },
        {
            "name": "f91",
            "f": lambda x: x * _sin(1 / x) - 0.1 - 0.01,
            "a": 0.01,
            "b": 1.0,
            "root": 0.120778011811926,
            "reported_n_fevals": 13,
            "n_clamped": 0,
        },
        {
            "name": "f92",
            "f": lambda x: x * x * x - 0.001,
            "a": -10.0,
            "b": 10.0,
            "root": 0.1,
            "reported_n_fevals": 25,
            "n_clamped": 0,
        },
    ]
]
